title: Zeqiang Wang
description: Personal Homepage of Zeqiang Wang
author: Zeqiang Wang
avatar: /Image/IMG_0037.PNG
email: zeqiang.wang@surrey.ac.uk
url: "https://zeqiangwangai.github.io"
baseurl: "/zqwang.github.io"

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: 
  card: summary
logo: logo.png
social:
  name: Zeqiang Wang
  links:
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
